### ISSUE TITLE
add SOP link

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#100]
Add SOP link to either 'Research' tab or maybe 'Dicty Stock Center' tab:
https://northwestern.app.box.com/s/p0f8m70whgiuib2u0wt8gtn497ncmq8i

![image](https://user-images.githubusercontent.com/29387347/96027350-5f430400-0e1d-11eb-8823-6a8e1cfed3c1.png)

**Comment by erichartline** [comment]
Added to the [navbar JSON](https://github.com/dictyBase/migration-data/blob/master/navbar/navbar.json). I moved it to the DSC dropdown since it is linked from the DSC homepage.
