### ISSUE TITLE
Login is not persisting on dictycr when using Safari (likely cross-site cookie blocking)

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#101]
When I login and then go to any page I want to edit (History, Techniques, Jobs...) the login disappears and I don't get the editor tools or the pen to get to the editor tools.  I'm using Safari and then tried Firefox, but i Firefox  not a single page turned up even, and it said unavailable. Strange as this wasn't the case when I started testing last week.

**Comment by erichartline** [comment]
This problem seems to be specific to `dictycr` and how browsers are handling cross-site cookies. Since our cookies are being set by `betagraphql.dictybase.org`, they are being [blocked](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/) for `dictycr.org` in Safari and Chrome.

**Comment by cybersiddhu** [comment]
Alright, then we have to have alias domains for dictycr.org, because third party cookie blocking is pretty standard measure for privacy. Though i think it is not on by default for chorme and definitely not for firefox, but safari always have a mind of its own.

**Comment by cybersiddhu** [comment]
Alright `betagraphql.dictycr.org` has been added to the dns, should be there within 10 mins.
So, you(@wildlifehexagon ) need to just add it to the ingress, map it to the graphql service and also rebuild and deploy the dsc app. I think that should solve it. Probably have to deploy it manually as i haven't checked the staging deployment yet.

**Comment by erichartline** [comment]
The Firefox issue that @pfey03 was having is described in more detail here: #102.

I updated this issue title to reflect the cross-site cookie problem specifically.

**Comment by erichartline** [comment]
The code fix has been merged into `develop`. Will leave this issue open until the Issuer/Ingress for staging has been updated accordingly.

**Comment by erichartline** [comment]
Since the remaining issue is related to our cluster configuration, I have moved it to [developer-docs](https://github.com/dictybase-docker/developer-docs/issues/224).
