### ISSUE TITLE
Add polyfill and custom browser list

### ISSUE THREAD

**Issue by erichartline** [dictyBase/dicty-stock-center#105]
To avoid further issues like #102, we should add [react-app-polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) and also add a list of browsers to support using `browserList`. Then if a user visits our site using an unsupported browser version, we display a notice and send a link for them to find a modern browser.

Further reading:
- https://create-react-app.dev/docs/supported-browsers-features/
- https://github.com/browserslist/browserslist-useragent
- https://github.com/browserslist/browserslist-useragent-regexp
- https://github.com/browserslist/browserslist

**Comment by erichartline** [comment]
This is something that could be added to [dicty-hooks](https://github.com/dictyBase/dicty-hooks) as `useSupportedBrowsers` or something similar.

**Comment by wildlifehexagon** [comment]
`react-app-polyfill` is already bundled with `react-scripts`

**Comment by erichartline** [comment]
Further thoughts:

- `browserslist-useragent` is meant for server side use
- `browserslist-useragent-regexp` has a bundle size of 53kb -- way too much for our apps

We are already using the `bowser` library to detect for IE. An optimal solution here is to use that inside of a custom hook.

**Comment by erichartline** [comment]
I looked at the data for browsers used by our users from the last six months.

Chrome - 62%
Safari - 19%
Firefox - 6%
Edge - 3%
IE - 2.5%

Even though such a small percentage use IE, we should still support it where possible. For DSC, we will need to add a polyfill for the intersection observer API and also redefine the `browserslist` config.

**Comment by erichartline** [comment]
The `intersection-observer` polyfill from W3C was added and the `browserlist` config was updated. I also removed the browser warnings and hardcoded browser versions.
