### ISSUE TITLE
match plasmid record to gene OR geneID in plasmid name

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#26]
many plasmids, especially those newer than about 2010, don't have a gene link. Not all plasmids contain a gene sequence, but those that do often have the gene name in the plasmid name.

Match those plasmids to gene, e.g.
https://eric.dictybase.dev/stockcenter/plasmids/DBP0001018

Gene_ID, although there is a gene name. But gene may have been named later.
https://eric.dictybase.dev/stockcenter/plasmids/DBP0001062

**Comment by erichartline** [comment]
The logic has been added so these gene names will display automatically on both strains and plasmid details pages. Once the latest data is loaded, this should be fixed.
