### ISSUE TITLE
display Gene Name on details page

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#27]
Update gene links on strain and plasmid detail pages to display Gene Names, when mapping is possible

**Comment by erichartline** [comment]
With the refactoring of the gene page to GraphQL, this should be possible to retrieve from another GraphQL query. Shouldn't need the endpoint from the previous comment.

**Comment by erichartline** [comment]
Reopening this -- let's use #78 specifically for strains that are missing their associated genes. This issue will be used to track gene IDs being converted to gene names.
