### ISSUE TITLE
add GoldenBraid plasmid list link to DSC page

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#323]
- GoldenBraid Google sheets link:
- https://docs.google.com/spreadsheets/d/1zg50MmBUKZx_AwDJ2-sNcxIvl_Lc1RfC/edit#gid=1498603553

- Maybe we can add links to the GWDI Remi site and GoldenBraid google sheet where the strain catalog and plasmid catalogs are also linked on the DSC front page:
![dsc_add_GWDI_catalog_golden_braid](https://user-images.githubusercontent.com/29387347/106940583-571e1580-66e7-11eb-8a73-8f572a6f0d60.png)

- We can also update the https://dictycr.org/stockcenter/information/order to include ordering steps for GWDI and GoldenBraid.

**Comment by erichartline** [comment]
@oimartin Good idea. Can you share the link for the GWDI Remi site too? Thanks!

**Comment by erichartline** [comment]
https://remi-seq.org/home/remi-seq/gwdi-bank/
