### ISSUE TITLE
On Strain Record change Genotypes to Genotype

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#391]
I just saw on a strain in test, that the field's name is 'Genotypes', but a strain has one genotype only and it should be just 'Genotype' like in the old database
https://testdb.dictybase.org/stockcenter/strains/DBS0351289
http://dictybase.org/db/cgi-bin/dictyBase/phenotype/strain_and_phenotype_details.pl?genotype_id=11881

Thanks!

ps.in the annotation table / tab delimited file I call it just Genotype without the plural.

**Comment by erichartline** [comment]
fixed in #392
