### ISSUE TITLE
Genotype display

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-stock-center#41]
Genotypes are typically formatted in italics, except the drug resistance(s) at the end.

Like this:
*_axeA1,axeB1,axeC1,dimB-,[bsRcas]_,bsR
*_axeA2,axeB2,axeC2,rrpB-,rrpC-,lacZ,[pDneo2a],RNAi-lacZ_,neoR,bsR

Can you do that automatic formatting?
Thanks!

Original issue: https://github.com/dictyBase/Migration/issues/99

**Comment by erichartline** [comment]
The last problem with the missing brackets is likely caused by old data. Once we update the data, this should be fixed.
