### ISSUE TITLE
on search, all plasmids and strains appear double

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#74]
When you search for a specific strain or plasmid, or a family with same stem of name, they are all listed double.

Search on plasmids e.g. for pDM314

**Comment by pfey03** [comment]
this seems fixed!

**Comment by pfey03** [comment]
oh no, it still pops up. First search all is fine, then clicked on a strain and publication. Then I searched for the same again and the strain I was on appears twice in the list

When you click on the box next to it then, both identical strains are clicked, so the database knows it's the identical strain. Strange behavior.

**Comment by erichartline** [comment]
This seems to be only happening for plasmids for some reason. Will need to write more unit tests for the catalogs to diagnose.
