### ISSUE TITLE
Checking Imgbot for Image Compression

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/dicty-stock-center#750]
This issue is related to Issue #747 . Essentially, part of what causes a lower total blocking time (TBT) score is downloading images and video. In the case of stockcenter, we use Imgbot to serve and compress the `jpeg` images. An alternate image type that Lighthouse recommends is using something like `jpeg 2000`, however, this image format is not fully supported by browsers at the moment. Instead, we can utilize the `webp` image format type, which according to my tests has reduced file sizes by a good 30-40%, with very minimal loss of quality.

The proposal of this issue is to have [Imgbot](https://imgbot.net/docs/) serve the images on the stockcenter homepage as `webp` instead of `jpeg`.

**Comment by cybersiddhu** [comment]
No longer required, as we are using next-gen image format with `picture` tag.
