### ISSUE TITLE
API For Next-gen Image Component

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/dicty-stock-center#752]
The purpose of this issue is to design an API for the next-gen image component. This component will be using the `picture` tag which allows browsers to use next-gen image formats, while also supporting older browsers with a fallback to `png` and `jpeg`.

### Component API
- `src`: Since the component will always need to have an `img` tag as the base, it must be _required_ to provide `src` which will correspond to the `src` attribute in the `img` tag within the parent `picture` tag
- `alt`: This prop will directly correspond to the image `alt` attribute
- `imgClassName`: This prop will directly correspond to the image `class` attribute
- `className`: Will provide the `class` attribute to the main `picture` tag
- `nextGenSources`: This prop corresponds to the `sources` tag with the parent `picture` tag
  - `srcSet`: corresponds with the `srcSet` attribute which takes in the next-gen image URL
  - `type`: corresponds with the `type` attribute, which can be either `"image/avif"` or `"image/webp"`

### Component Prop Implementation
```ts
type PictureSource = {
  srcSet: string
  type: "image/webp" | "image/avif"
  orientation?: "landscape" | "portrait"
}

type DictyImageProps = {
  src: string
  nextGenSources?: PictureSource[]
  alt?: string
  id?: string
  imgClassName?: string
  className?: string
}
```

With this implementation the usage of this component will look like this:
```jsx
<NextGenImage 
  src="img.jpg"
  alt="my image"
  nextGenSources={[
    { srcSet: "img.webp", type: "image/webp" },
    { srcSet: "img.avif", type: "image/avif" },
  ]}
/>
```
This should generate the following HTML:
```html
<picture>
  <source media="(orientation: landscape)" srcset="img.webp" type="imgage/webp">
  <source media="(orientation: landscape)" srcset="img.avif" type="imgage/avif">
  <img src="img.jpg" alt="my image">
</picture>
```

**Comment by cybersiddhu** [comment]
Needs a little tweak. 
Lets not redefine the `HTMLImageElement`, reuse that for our purpose as `<picture>` uses a html image element. Now the `HTMLImageElement` could be another custom wrapper  component that can provided some additional functionality if needed. Otherwise, a `html image` tag will suffice.
```ts
type DictyImageProps = {
  fallbackSource: HTMLImageElement,
  nextGenSources?: PictureSource[]
}
```
```jsx
<NextGenImage 
  fallbackSource = { imageElementVar },
  nextGenSources={[
    { srcSet: "img.webp", type: "image/webp" },
    { srcSet: "img.avif", type: "image/avif" },
  ]}
/>
```

**Comment by ayaanqui** [comment]
@cybersiddhu I'm having some trouble with getting `HTMLImageElement` to work with the component. Since it looks like we have to use `new Image()` then set each attribute. I'm trying to see it there's a way to pass in an image element directly.

```jsx
<DictyImage
  fallbackSource={ <img src="img.jpg" /> }
/>
```

**Comment by cybersiddhu** [comment]
```js
type DictyImageProps = {
  children: JSX.IntrinsicElements["img"],
  nextGenSources?: PictureSource[]
}
```

**Comment by ayaanqui** [comment]
@cybersiddhu proposed the use of `Pick<React.ImgHTMLAttributes<HTMLImageElement>, "src" | "alt">` instead of `HTMLImageElement` as it takes in the proper `img` element.

**Comment by ayaanqui** [comment]
During the weekend, I asked a question on StackOverflow about the `IntrinsicAttributes` type errors, which I recreated on this [code sandbox](https://codesandbox.io/s/async-architecture-30q4s?file=/src/App.tsx). On there I was told that TS does not support HTML types properly and that I should instead pass the props for the element instead, by extending the Prop type with `React.ImgHTMLAttributes<HTMLImageElement>`. Here's the [code sandbox](https://codesandbox.io/s/new-water-pe59e?file=/src/App.tsx) that uses attributes instead of passing `children`. @cybersiddhu Let me know what you think of this.

**Comment by ayaanqui** [comment]
[https://stackoverflow.com/questions/69775746/typescript-expected-type-comes-from-property-children-which-is-declared-on-i](https://stackoverflow.com/questions/69775746/typescript-expected-type-comes-from-property-children-which-is-declared-on-i)
