### ISSUE TITLE
on strain or plasmid search add number of listed on top?

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-stock-center#77]
we have a total count in the current/old dictyBase after search
DSC search:
http://dictybase.org/db/cgi-bin/dictyBase/SC/scsearch.pl?searchdb=strains&search_term=*sadA*&column=name&B1=Submit

General gene search
http://dictybase.org/db/cgi-bin/search/results.pl?class=dicty::UI::Search::Gene&query=abp*

Thanks!

**Comment by pfey03** [comment]
It should also appear on the total list, the number

**Comment by erichartline** [comment]
this will be solved with #355
