### ISSUE TITLE
Adjust add to cart button/logo

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#80]
Currently, just the cart logo is used to add an item to the cart
![image](https://user-images.githubusercontent.com/29387347/95486485-ab430400-0958-11eb-97dc-02a8f624518a.png)

Would it be possible to make it look like this
![Adjusted_add_to_cart](https://user-images.githubusercontent.com/29387347/95487370-d8dc7d00-0959-11eb-98ae-ccc6f9253d8f.png)

**Comment by cybersiddhu** [comment]
Yeah it's possible, however the icon is self explanatory and also has a tooltip to explain that. Not sure, why we have to make it explicit.
