### ISSUE TITLE
Download / View links give raw data

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#95]
From the stock center home page, the Download / View links, 
- Phenotype Ontology
- Strain Characteristics
- Mutagenesis Methods
- Plasmid Keywords

![image](https://user-images.githubusercontent.com/29387347/96019731-8a742600-0e12-11eb-93c7-1833c024ddf8.png)

When you click the link it just shows this: 
![Screen Shot 2020-10-14 at 11 46 16 AM](https://user-images.githubusercontent.com/29387347/96019842-babbc480-0e12-11eb-8d41-24bb3686c719.png)
https://raw.githubusercontent.com/dictyBase/migration-data/master/ontologies/dicty_phenotypes.obo

**Comment by pfey03** [comment]
@oimartin, @wildlifehexagon This is ok to give the ontology in obo format. It's like it's available anywhere out there, in addition to json and owl, which are not so humanely readable. I would not create any other format for ontologies, as for those interested, they should be able to use these.

**Comment by pfey03** [comment]
any other website could not be comprehensive and for ontology interested, complete and can be opened in Protege. A page like this for anatomy http://dictybase.org/Dicty_Info/dicty_anatomy_ontology.html
we don't need to transfer this in my book. Anatomy has a paper out there and who wants more should just use the ontology

**Comment by erichartline** [comment]
@pfey03, @oimartin

I can leave these as is for now then. One thing we could do is make the links open in a new tab, that way the users still stay on our site without having to click back. What do you think?
