### ISSUE TITLE
Include bacterial food strains in drop down on strain catalog page

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#96]
Could be helpful to also include 'bacterial food strains' in addition to the current options. 

![image](https://user-images.githubusercontent.com/29387347/96020575-dd021200-0e13-11eb-85b6-357df75fa032.png)

**Comment by erichartline** [comment]
This has been added to the dropdown. Progress related to adding in the logic to display the results from this filter will be added in #36
