### ISSUE TITLE
email link for DSC + contact link on bottom

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#97]
![image](https://user-images.githubusercontent.com/29387347/96022146-0885fc00-0e16-11eb-9172-033098604c99.png)
https://dictycr.org/stockcenter/information/order

![image](https://user-images.githubusercontent.com/29387347/96022598-b5607900-0e16-11eb-89ea-41e09c3a7e41.png)
https://dictycr.org/stockcenter/information/deposit

![image](https://user-images.githubusercontent.com/29387347/96023021-68c96d80-0e17-11eb-80bd-e5b0bc6c715f.png)
at the bottom of every page

- Will we have recaptcha or link to a form with recaptcha? Could we also display DSC email like this : 
dictystocks AT northwestern.edu ? or link to https://dictycr.org/stockcenter/contact

**Comment by erichartline** [comment]
I added the email links on the information pages. The footer link can be added to our condensed footer -- moving that particular issue to https://github.com/dictyBase/dicty-components-header-footer/issues/310
