### ISSUE TITLE
Create separate shipping information page

### ISSUE THREAD

**Issue by oimartin** [dictyBase/dicty-stock-center#99]
This would be helpful to have a separate page given all of the different issues we have learned from in the past year in addition to the 'Additional Shipping Information' listed on the Deposit Information page, https://dictycr.org/stockcenter/information/deposit 

![image](https://user-images.githubusercontent.com/29387347/96025163-60befd00-0e1a-11eb-8101-a40edc5c01ee.png)

![image](https://user-images.githubusercontent.com/29387347/96025152-5d2b7600-0e1a-11eb-8495-6041c1a7a999.png)
________
I can go into detail about how we ship and then we can just link to the 'Shipping Information' to the 'Deposit Information' page and on the FAQ page.

**Comment by pfey03** [comment]
For the actual page and when editing is fully functional @oimartin I can work with you what you want and you can send me the text. Once the page is there, the link might be added to dropdown.

**Comment by erichartline** [comment]
This has been set up here: https://testdb.dictybase.org/stockcenter/information/shipping

I will add a link on the homepage, then once it is ready I'll add a link in the navbar.
